version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: department_db
    restart: always
    environment:
      POSTGRES_DB: department_db
      POSTGRES_PASSWORD: postgres
    ports: ["5434:5432"]